### ISSUE TITLE
Is it possible to save the whole response document as json object?

### ISSUE THREAD

**Issue by oakkas** [googleapis/python-documentai#102]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

 **Is your feature request related to a problem? Please describe.**
I would love to save all the content of the response as a json object.
 **Describe the solution you'd like**
Being able to easily save the response document object
 **Describe alternatives you've considered**
As an alternative I have to iterate over all the objects in the document and get each calue.

**Comment by munkhuushmgl** [comment]
@oakkas 

Here is the snippet you can use for converting:

```
from google.protobuf.json_format import MessageToJson

// build request

.. code for building request

// send the request
    result = client.process_document(request=request)

// convert the response into JSON
    json_response = MessageToJson(result._pb)
    print(json_response)

```

With that note, I am closing this issue. Feel free to reopen if you are still experiencing the same issue.

**Comment by oakkas** [comment]
@munkhuushmgl Thanks a lot. It works great.
