### ISSUE TITLE
Batch parse form doesn't save response json files

### ISSUE THREAD

**Issue by oakkas** [googleapis/python-documentai#109]
- OS type and version: Debian-9
  - Python version: `python --version`: Python 3.7.2
  - pip version: `pip --version`: pip 19.0.3
  - `google-cloud-documentai` version: `pip show google-cloud-documentai`: 0.3.0

#### Steps to reproduce

  Running the https://github.com/googleapis/python-documentai/blob/master/samples/snippets/batch_parse_form_v1beta2.py with documents in the GCP bucket

**Comment by munkhuushmgl** [comment]
Could you share the input file was to make this request ? [If it is data sensitive, please remove sensitive values and replace with dumb values]

**Comment by munkhuushmgl** [comment]
Looks like it is working as intended
![image](https://user-images.githubusercontent.com/45373284/113035565-32bf4200-9148-11eb-9c59-c8d31c9f47a5.png)

Did you make sure that you output dir was provided?
```
batch_parse_form("YOUR_GCP_PROJECT", "gs://cloud-samples-data/documentai/form.pdf", "gs://output_bucket/output_dir_folder/")
```

**Comment by oakkas** [comment]
@munkhuushmgl Thanks for the response.
I can't share the original one but I have a fake one. 
[WC164_Physicians_Report_of_Injury_1.pdf](https://github.com/googleapis/python-documentai/files/6231230/WC164_Physicians_Report_of_Injury_1.pdf)

**Comment by oakkas** [comment]
Here is my request:
input_config {
  gcs_source {
    uri: "gs://mrcm-pipeline-sandbox-us-central1-medrec-images/unprocessed/10095585-99805484_03_08_2021-67445903-MEDICAL_RECORD.pdf"
  }
  mime_type: "application/pdf"
}
output_config {
  gcs_destination {
    uri: "gs://lake-confidential-tst-medrec-text-raw/responses/10095585-99805484_03_08_2021-67445903-MEDICAL_RECORD/"
  }
  pages_per_shard: 1
}
form_extraction_params {
  enabled: true
  key_value_pair_hints {
    key: "Date of Injury"
    value_types: "DATE"
  }
  key_value_pair_hints {
    key: "Date of Birth"
    value_types: "DATE"
  }
  key_value_pair_hints {
    key: "Insurer Claim #"
    value_types: "NUMBER"
  }
  key_value_pair_hints {
    key: "Injured Worker"
  }
}

and here is the batch_requests:

requests {
  input_config {
    gcs_source {
      uri: "gs://mrcm-pipeline-sandbox-us-central1-medrec-images/unprocessed/10095585-99805484_03_08_2021-67445903-MEDICAL_RECORD.pdf"
    }
    mime_type: "application/pdf"
  }
  output_config {
    gcs_destination {
      uri: "gs://lake-confidential-tst-medrec-text-raw/responses/10095585-99805484_03_08_2021-67445903-MEDICAL_RECORD/"
    }
    pages_per_shard: 1
  }
  form_extraction_params {
    enabled: true
    key_value_pair_hints {
      key: "Date of Injury"
      value_types: "DATE"
    }
    key_value_pair_hints {
      key: "Date of Birth"
      value_types: "DATE"
    }
    key_value_pair_hints {
      key: "Insurer Claim #"
      value_types: "NUMBER"
    }
    key_value_pair_hints {
      key: "Injured Worker"
    }
  }
}
requests {
  input_config {
    gcs_source {
      uri: "gs://mrcm-pipeline-sandbox-us-central1-medrec-images/unprocessed/10095585-99805484_03_16_2021-76898765-MEDICAL_RECORD.pdf"
    }
    mime_type: "application/pdf"
  }
  output_config {
    gcs_destination {
      uri: "gs://lake-confidential-tst-medrec-text-raw/responses/10095585-99805484_03_16_2021-76898765-MEDICAL_RECORD/"
    }
    pages_per_shard: 1
  }
  form_extraction_params {
    enabled: true
    key_value_pair_hints {
      key: "Date of Injury"
      value_types: "DATE"
    }
    key_value_pair_hints {
      key: "Date of Birth"
      value_types: "DATE"
    }
    key_value_pair_hints {
      key: "Insurer Claim #"
      value_types: "NUMBER"
    }
    key_value_pair_hints {
      key: "Injured Worker"
    }
  }
}
parent: "projects/z12ff-4d53-3865/locations/us"

**Comment by munkhuushmgl** [comment]
Sorry it took me while to respond back but looks like I was able to save response in json format with your given input
![image](https://user-images.githubusercontent.com/45373284/117494314-ffcb5380-af28-11eb-8a87-0fd1cea93bee.png)
