### ISSUE TITLE
Is it possible to output the results similar to an input document

### ISSUE THREAD

**Issue by oakkas** [googleapis/python-documentai#110]
I am trying to get a similar format as an input document. I assume this would be possible to use bounding_poly and normalized_vertices in the response. I am just not sure how to turn vertices into actual pixel locations yet. If someone has a code snippet, that would be awesome.

**Comment by munkhuushmgl** [comment]
Could you illustrate this with example code snippet?

**Comment by oakkas** [comment]
Trying to do something close to this image. So structuring the output as they are found in the image/document location.

![Form_Parser_analysis_–_Document_AI_–_aas-ds-default_–_Google_Cloud_Platform](https://user-images.githubusercontent.com/13190903/113177859-3536a000-920b-11eb-8a6a-ceb9ebbfdff3.png)

**Comment by telpirion** [comment]
Hello @oakkas , you might look at [this demo/notebook](https://github.com/GoogleCloudPlatform/documentai-notebooks).
