### ISSUE TITLE
How to train/provide "model_version" for FormExtractionParams ( google.cloud.documentai_v1beta2.types.FormExtractionParams)

### ISSUE THREAD

**Issue by arijit-s** [googleapis/python-documentai#123]
Hi,

As per the [API documentation](https://googleapis.dev/python/documentai/0.4.0/documentai_v1beta2/types.html#google.cloud.documentai_v1beta2.types.FormExtractionParams) for v1beta2 there is a provision to provide custom model id /annotation dataset for FormExtraction, 

> **model_version**
> Model version of the form extraction system. Default is “builtin/stable”. Specify “builtin/latest” for the latest model. For custom form models, specify: “custom/{model_name}”. Model name format is “bucket_name/path/to/modeldir” corresponding to “gs://bucket_name/path/to/modeldir” where annotated examples are stored.

Is there any documentation or guideline available on how to train the model or prepare the annotated dataset which can be put into gs bucket and referred in the model_version parameter?

**Comment by telpirion** [comment]
Hello @arijit-s, it looks like you have a question about the API design itself.  This GitHub repo is for client library and samples alone. I suggest that you direct your question to one of the channels mentioned [here](https://cloud.google.com/document-ai/docs/getting-support).
