### ISSUE TITLE
Normalized values

### ISSUE THREAD

**Issue by edumotya** [googleapis/python-documentai#136]
The pattern ```r"\d\d.0\d"``` is not properly normalized. I mean, the normalized values of amount and unit price entities are not correctly parsed when the decimal digit is 0 and the centesimal digit is different from 0. For instance, the text "18.02" is parsed with the normalized_value of "18.2" instead of "18.02". 

#### Environment details

OS type and version:
Python version: 3.6.12
pip version: 20.2.4
google-cloud-documentai version: 0.4.0

#### Example

```proto
properties {
  text_anchor {
    text_segments {
      start_index: 2079
      end_index: 2084
    }
    content: "39,05"
  }
  type_: "line_item/amount"
  mention_text: "39,05"
  confidence: 0.9064523577690125
  page_anchor {
    page_refs {
      page: 1
      bounding_poly {
        normalized_vertices {
          x: 0.8506841063499451
          y: 0.7494745850563049
        }
        normalized_vertices {
          x: 0.8792385458946228
          y: 0.7494745850563049
        }
        normalized_vertices {
          x: 0.8792385458946228
          y: 0.7591425180435181
        }
        normalized_vertices {
          x: 0.8506841063499451
          y: 0.7591425180435181
        }
      }
    }
  }
  id: "12"
  normalized_value {
    text: "39.5"
    money_value {
      units: 39
      nanos: 50000000
    }
  }
}
```

**Comment by telpirion** [comment]
Hi @edumotya , this looks like a product issue rather than a Python client library issue. Can you please confirm?

**Comment by edumotya** [comment]
Hi @telpirion, sure, this is a product issue. This has nothing to do with the client library. How we proceed? should I open a ticket in GCP?

**Comment by telpirion** [comment]
Okay, it looks like you'll want to follow the directions [here](https://cloud.google.com/support/docs/manage-cases#creating_cases) and select the following:

* Group: Machine Learning
* Component: Document AI
* Subcomponent: (processor)
