### ISSUE TITLE
DocAI: transient error not retried

### ISSUE THREAD

**Issue by yiga2** [googleapis/python-documentai#142]
Using v1beta3, client lib v0.4.0, `process_document()` (the sync version) does not retry when hitting transient error `RESOURCE_EXHAUSTED`

We have a cloud function that processes pdf files as they get copied to `GCS`. Sometimes depending on the load, we hit unsurprisingly the quota limit `Quota exceeded for quota metric 'Number of online process document requests using document processor' and limit 'Number of online process document requests using document processor per minute' of service 'documentai.googleapis.com' for consumer 'project_number:xxxx'.  `

Such "error" is retriable (grpc status 8) and should be retried by default, however it does not and function stops with:
![image](https://user-images.githubusercontent.com/25224265/117710698-6ad28f80-b1a0-11eb-8a1c-b7ecc36a24a5.png)

I don't have a snippet to reproduce w/o GCF but a simple looping (async ?) at high rate should trigger the quota error.

**Comment by yiga2** [comment]
Workaround using `backoff` library until fixed:
```
from google.api_core.exceptions import ResourceExhausted
import backoff`
```
... and wrap the `process_document()` (and possibly other service calls) into a function decorated with
```
@backoff.on_exception(backoff.expo, ResourceExhausted)
```

**Comment by munkhuushmgl** [comment]
Hello @yiga2 

Thanks for loggin this issue,

Correct me if i am wrong:

so you have GCF that runs at high number of times in a certain period of time, and it fails sometimes due to GRPC status 8.
After hitting the resource exhausted error, you run right after and expecting the function to run without any error?

Is that correct?

**Comment by yiga2** [comment]
A http 429 or grpc 8 error is typically due to hitting a quota limit (here 120 requests/sec) so it safely can be retried later (e.g. exponential backoff).

Other GCP libraries leverage https://googleapis.dev/python/google-api-core/latest/retry.html#google.api_core.retry.Retry without the user specifying which errors should be retried e.g. https://github.com/googleapis/python-bigquery/blob/master/google/cloud/bigquery/retry.py

Maybe `process_document(retry=...)` parameter can be used for that but it's unclear w/o snippet or documentation.

In doubt, I like to use `backoff` as per above workaround. With the logging option, I can also see the retries in the logs:
![image](https://user-images.githubusercontent.com/25224265/117873270-966f7b80-b26d-11eb-9338-8cdf0525088f.png)

**Comment by munkhuushmgl** [comment]
I am not sure we will write a snippet for demonstrating this problem.

I think you can do something like this :
```
from google.api_core import exceptions
from google.api_core import retry

retry_commit = retry.Retry(
    predicate=retry.if_exception_type(exceptions.RESOURCE_EXHAUSTED),
    deadline=60)

...

retry(client.process_document(request=request))
```
Further information please refer to the docs
https://googleapis.dev/python/google-api-core/latest/retry.html#google.api_core.retry.Retry

**Comment by yiga2** [comment]
I guess what I am saying is that DocAI lacks a default retry logic, like BigQuery (link earlier) or [Storage ](https://github.com/googleapis/python-storage/blob/master/google/cloud/storage/retry.py)

For consistency and setting expectations when user sees the retry parameter, DocAI should have a similar default retry for all methods too e.g. `process_document(retry=DEFAULT_RETRY)`. This would cover any transient error.

Feel free to close if you don't want to implement as I am happy with using the `backoff` library as I get logging.

**Comment by yiga2** [comment]
I want to reopen this issue - or do I need to create a new one. I insist on using the built-in `Retry()` dependency that exists in all G-apis libraries.
Cross-referencing https://github.com/googleapis/python-api-core/issues/337 in case the issue is with `Retry()`.
