### ISSUE TITLE
Internal error encountered with sample test_batch_process_documents_with_bad_input

### ISSUE THREAD

**Issue by parthea** [googleapis/python-documentai#244]
In the last 2 days, the samples test [test_batch_process_documents_with_bad_input](https://github.com/googleapis/python-documentai/blob/main/samples/snippets/batch_process_documents_sample_bad_input_test.py#L30) has been failing with 
```
>           assert "Failed to process" in e.message
E           AssertionError: assert 'Failed to process' in 'Internal error encountered.'
E            +  where 'Internal error encountered.' = InternalServerError('Internal error encountered.',).message
```

See the build log [here](https://source.cloud.google.com/results/invocations/aba8b613-3e3b-4d55-87f5-598842a7b8a3/log).

**Comment by galz10** [comment]
@parthea It looks like this problem is caused by ``` 500 Internal error encountered. ```

**Comment by galz10** [comment]
Created a buganizer issue with the eng team

**Comment by galz10** [comment]
This should be fixed, public errors are returned now.

**Comment by parthea** [comment]
This issue has returned. See build log [here](https://source.cloud.google.com/results/invocations/4a5ad72c-4443-4735-9b09-15a922c58b42/log).
