### ISSUE TITLE
Cannot initialize documentai_v1beta2.types.Document

### ISSUE THREAD

**Issue by jodrodriguezpo** [googleapis/python-documentai#36]
Hi, first of all thank you for this library. It has been very useful. However I'm having the following problem:
  
Is there any way to read a response generated by documentai_v1beta2.DocumentUnderstandingServiceClient().batch_process_documents(batch_request) as a documentai_v1beta2.types.Document object?

I followed the steps in https://cloud.google.com/document-ai/docs/process-tables#documentai_batch_parse_table-python for large files, and the json response is generated correctly in my bucket. However I am unable to read the response as a documentai_v1beta2.types.Document to manipulate it more easily.

#### Environment details

  - OS type and version:
  - Python version: 3.7.8
  - pip version: 20.1.1
  - `google-cloud-documentai` version: 0.2.0

#### Steps to reproduce

  1. Create a response for a large image as shown in https://cloud.google.com/document-ai/docs/process-tables#documentai_batch_parse_table-python . This generates a json response in my bucket. The file has all the fields corresponding to a Document json representation.

  2. Read response as json with blob and json.loads.

  3. Initialize documentai_v1beta2.types.Document object using the json object as mapping parameter.

#### Code example

```
def process_document_with_ai(ai_request, destination_uri):
    if not destination_uri:
        return DOCUMENTAI_CLIENT.process_document(
            request=ai_request
        )
    else:
        operation = DOCUMENTAI_CLIENT.batch_process_documents(
            ai_request
        )

        operation.result()

        match = re.match(r'gs://([^/]+)/(.+)', destination_uri)
        prefix = match.group(2)

        blob_list = list(bucket.list_blobs(prefix=prefix))

        return blob_list[0].download_as_string()

processed_document = image_table_extraction.process_document_with_ai(
    ai_request, destination
)

json_file = json.loads(processed_document)

doc_test = documentai.types.Document(
    mapping=json_file
)
```

#### Stack trace
```
KeyError                                  Traceback (most recent call last)
<ipython-input-72-56f0ad5dfc37> in <module>
      1 doc_test = documentai.types.Document(
----> 2     mapping=json_file
      3 )

/opt/conda/lib/python3.7/site-packages/proto/message.py in __init__(self, mapping, **kwargs)
    415         marshal = self._meta.marshal
    416         for key, value in mapping.items():
--> 417             pb_type = self._meta.fields[key].pb_type
    418             pb_value = marshal.to_proto(pb_type, value)
    419             if pb_value is not None:

KeyError: 'mimeType'`
# example
```

**Comment by busunkim96** [comment]
Hi @jodrodriguezpo,

If I'm understanding correctly, you're trying to turn a JSON representation of a Document back into a library type?

Could you try upgrading your `proto-plus` version? `pip install --upgrade proto-plus`? I think the real error may be hidden away if you are on an older version of proto plus. 

Unfortunately you will likely still be bitten by https://github.com/googleapis/proto-plus-python/issues/81 since the Document type has enums in it.

**Comment by jodrodriguezpo** [comment]
Hi again @busunkim96,

Yes that's what im trying to do. I already updated `proto-plus` to `1.6.0` version, and still get the same trace.

**Comment by busunkim96** [comment]
@jodrodriguezpo Unfortunately I think you'll have to wait for https://github.com/googleapis/proto-plus-python/issues/52 to be resolved. It's currently slated to be fixed in September.

**Comment by jodrodriguezpo** [comment]
@busunkim96 I'll subscribe to that issue. Thank you for your help.
