### ISSUE TITLE
A 'type' field of entity is always empty

### ISSUE THREAD

**Issue by AlexanderKomarov** [googleapis/python-documentai#37]
I'm trying to use Google Document AI for getting data from a PDF file. But a 'type' field of entity is empty always. But it must be non-empty according to the [documentation](https://googleapis.dev/python/documentai/latest/_modules/google/cloud/documentai_v1beta2/types/document.html#Document.Entity).

#### Environment details

  - Mac OS X - 10.15.6
  - Python version: 3.7.6
  - pip version: 19.3.1
  - `google-cloud-documentai` version: 0.2.0

#### Code example
My code is based on the [Codelabs tutorial](https://codelabs.developers.google.com/codelabs/document-ai-overview/index.html?index=..%2F..index#6)
```python
from google.cloud import documentai_v1beta2 as documentai

def parse_invoice(project_id='myprojectid',
         input_uri='gs://cloud-samples-data/documentai/invoice.pdf'):
    """Procsingle document with the Document AI API, including
    text extraction and entity extraction."""

    client = documentai.DocumentUnderstandingServiceClient()

    gcs_source = documentai.types.GcsSource(uri=input_uri)
    # mime_type can be application/pdf, image/tiff,
    # and image/gif, or application/json
    input_config = documentai.types.InputConfig(
        gcs_source=gcs_source, mime_type='application/pdf')

    entity_p = documentai.types.EntityExtractionParams(enabled=True)
    parent = 'projects/{}/locations/us'.format(project_id)
    
    request = documentai.types.ProcessDocumentRequest(
        parent=parent,
        input_config=input_config,
        entity_extraction_params=entity_p)
    document = client.process_document(request=request)
    print(document.entities)
```

Here is a part of output:
```
, text_anchor {
  text_segments {
    start_index: 273
    end_index: 303
  }
}
mention_text: "John Doe\njohndoe@email.com"
mention_id: "6"
confidence: 0.8736821413040161
```

Does anybody know where can be a problem?

**Comment by busunkim96** [comment]
@AlexanderKomarov Hi, are you expecting `type` to be populated in the response entity?  I'm not able to find that requirement in the [API docs](https://cloud.google.com/document-ai/docs/reference/rpc/google.cloud.documentai.v1beta2#entity) or the library docs.

I believe printing the proto will skip fields that aren't set, but it is still accessible e.g., `entity.type` should not error.

**Comment by AlexanderKomarov** [comment]
Thank you for the quick response @busunkim96 
Yes, I was expecting to get something like that "Address", "email", "Phone number". According to the documentation:

`type - Entity type from a schema e.g. Address.`

I was going to use it for analyzing a document. Perhaps there is another way to get an entity type.

**Comment by busunkim96** [comment]
@dalequark Could you take a look?

**Comment by roman-borodinov** [comment]
@AlexanderKomarov @busunkim96 
I faced the same problem. Trying to use invoice parser (when using the sample from docs https://cloud.google.com/document-ai/docs/invoice-parser).
1) You are receiving the same info as on the test page https://cloud.google.com/document-ai/docs/drag-and-drop (if you select the "invoice" option) the type of entities might be filled (at last it worked for me)
2) there is an option that sends with CURL request and missed in the sample
    request = documentai.types.ProcessDocumentRequest(
        parent=parent,
        input_config=input_config,
        document_type='invoice')

document type must be set to use invoice parser (but before it never worked for me I always got "invoice" is not allowed for your project even after apply required form and got permission)
3) you need to receive permissions to use it. (fill the form  "Document AI limited access customer request form" on https://cloud.google.com/document-ai/docs/invoice-parser page)

**Comment by telpirion** [comment]
Thank you for filing this issue. It sounds like your issue has been resolved.

Also, note that the current version of the Document AI service is `v1beta3`, which introduces the concept of parsers. Please migrate your solutions to `v1beta3`, as `v1beta2` is no longer considered the most up-to-date version of the service.
