### ISSUE TITLE
Can't specify latest model for form extraction

### ISSUE THREAD

**Issue by tuanardouin** [googleapis/python-documentai#40]
Hello,

#### Environment details

  - Python version: Python 3.8.2
  - pip version:  pip 20.0.2
  - `google-cloud-documentai` version: 0.2.0

#### Code example

```python
form_extraction_params = documentai.types.FormExtractionParams(
        enabled=True, key_value_pair_hints=key_value_pair_hints, model_version='builtin/latest')
```

#### Stack trace
```
google.api_core.exceptions.InvalidArgument: 400 Invalid form model version. Must either start with custom/ or gs://
```

Thanks

**Comment by telpirion** [comment]
Hello @tuanardouin, 'builtin/latest' currently isn't being used. You will always receive the most stable version of the parser. 

You also might consider migrating your solution to v1beta3 version of the service, as it includes the latest enhancements and improvements to the service.
