### ISSUE TITLE
Operation set_default_processor_version not implemented

### ISSUE THREAD

**Issue by guillem-cy** [googleapis/python-documentai#422]
I am trying to use the `set_default_processor_version` method from the v1 beta 3 client: https://cloud.google.com/python/docs/reference/documentai/latest/google.cloud.documentai_v1beta3.services.document_processor_service.DocumentProcessorServiceClient#google_cloud_documentai_v1beta3_services_document_processor_service_DocumentProcessorServiceClient_set_default_processor_version

I am getting a 501 error:

```
google.api_core.exceptions.MethodNotImplemented: 501 Operation is not implemented, or supported, or enabled
```

I am doing it like this:

```
request = documentai_v1beta3.SetDefaultProcessorVersionRequest(
    processor="projects/project_id/locations/location/processors/proc_id", 
    default_processor_version="projects/project_id/locations/location/processors/proc_id/processorVersions/version_id"
)
operation = gcp_docai_client.set_default_processor_version(request=request)
operation.result()
```

Am I doing something wrong? Is this operation implemented?

**Comment by holtskinner** [comment]
It should be implemented, try following this sample instead (using the `v1` endpoint)

https://cloud.google.com/document-ai/docs/samples/documentai-set-default-processor-version
