### ISSUE TITLE
Update samples to use v1beta3

### ISSUE THREAD

**Issue by aribray** [googleapis/python-documentai#50]
@telpirion, feature request to bump samples version from `v1beta2` -> `v1beta3`

**Comment by telpirion** [comment]
It looks like all of these samples are already using v1beta3.

Looking at the [old samples](https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/document/cloud-client), it looks like they are correctly using v1beta2. 

I'm going to close this work item. Thank you for tracking this tho!
