### ISSUE TITLE
Clause in "IF IN" statement is incorrect..gives wrong start index for the text segment 

### ISSUE THREAD

**Issue by rajatgupta143** [googleapis/python-documentai#53]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/python-documentai/issues
  - Search StackOverflow: https://stackoverflow.com/questions/tagged/google-cloud-platform+python

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS type and version: AI Notebooks
  - Python version: `python --version`: 3.7
  - pip version: `pip --version`: pip 20.1.1 from /opt/conda/lib/python3.7/site-packages/pip (python 3.7)
  - `google-cloud-documentai` version: `pip show google-cloud-documentai`

jupyter@python-20200630-170900:~$ pip show google-cloud-documentai
Name: google-cloud-documentai
Version: 0.3.0
Summary: UNKNOWN
Home-page: https://github.com/googleapis/python-documentai
Author: Google LLC
Author-email: googleapis-packages@google.com
License: Apache 2.0
Location: /opt/conda/lib/python3.7/site-packages
Requires: google-api-core, proto-plus
Required-by: 

#### Steps to reproduce

  1. Run the code listed at https://cloud.google.com/document-ai/docs/invoice-parser --> Small File Processing --> Python
  2. get_text methos gives the start index always to be 0. That causes the extracted text to be more than required. 

#### Code example

```python
# example

start_index = (
            int(segment.start_index)
            if segment.start_index in doc_element.text_anchor.text_segments # this is the problem code
            else 0
        )
```

Suggested update to the above:
start_index = (
            int(segment.start_index)            
            if segment in doc_element.text_anchor.text_segments else 0
        )

#### Stack trace
```
# example
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by munkhuushmgl** [comment]
I need to test this locally and verify all requirements and tests are passing.
Once they pass, I will create PR with this change.

**Comment by munkhuushmgl** [comment]
@rajatgupta143 thanks for logging this issue.
