### ISSUE TITLE
EU location not supported

### ISSUE THREAD

**Issue by QMichard** [googleapis/python-documentai#55]
Hi,
The location 'eu' doesn't seem to be supported by the client.

#### Environment details
  - OS type and version: Chromebook 86.0
  - Python version: Python 3.7.3
  - pip version: pip 18.1 
  - `google-cloud-documentai` version: 0.3.0

#### Steps to reproduce

https://github.com/googleapis/python-documentai/blob/master/samples/snippets/process_document_sample_v1beta3_test.py
with the location set to 'eu'

The base url "us-documentai.googleapis.com" seems hardcoded in the code. 
https://github.com/googleapis/python-documentai/search?q=us-documentai&type=code

the correct url looks like 
https://**eu**-documentai.googleapis.com/v1beta3/projects/123456789/locations/**eu**/processors/azerty:process

#### Stack trace

google.api_core.exceptions.PermissionDenied: 403 Permission 'documentai.processors.processOnline' denied on resource '//documentai.googleapis.com/projects/1234567890/locations/eu/processors/azerty' (or it may not exist).

Thanks!

**Comment by munkhuushmgl** [comment]
@QMichard you have to modify the endpoint to europe region.

like following:

```
client_options = {"api_endpoint": "eu-central1-aiplatform.googleapis.com"}
    client = aiplatform.gapic.ModelServiceClient(client_options=client_options)
```

note: i made region up.

**Comment by QMichard** [comment]
Hi @munkhuushmgl 
Thanks for your quick reply and it's correct. The exact change is : 
```
client_options = {"api_endpoint": "eu-documentai.googleapis.com"}
client = documentai.DocumentProcessorServiceClient(client_options=client_options)
```
