### ISSUE TITLE
text_styles empty

### ISSUE THREAD

**Issue by edumotya** [googleapis/python-documentai#73]
#### Environment details

  - OS type and version:
  - Python version: 3.6.12
  - pip version: 20.2.4
  - `google-cloud-documentai` version: 0.3.0

I found that some fields are always empty. I want to read the field text_styles but it always provides an empty list.

#### Code example

```python
client = documentai.DocumentProcessorServiceClient()
request = documentai.types.ProcessRequest(
        name=name,
        document=documentai.types.Document(content=content, mime_type=mime_type),
    )
result = client.process_document(request=request, timeout=DOCUMENTAI_TIMEOUT)
document = result.document
print(document.text_styles) # [ ] empty list
```

**Comment by munkhuushmgl** [comment]
@edumotya I was able to repro this problem.

I will request this feature internally.
Cannot give you ETA but once i get response back, I will inform you

thanks for reporting this.

**Comment by edumotya** [comment]
Thank you @munkhuushmgl. This feature is important for our team. We can also create a ticket in the google cloud support console if necessary, do you think it would hasten the resolution of the case?

**Comment by munkhuushmgl** [comment]
@edumotya Yes, that might help you. However, during the holiday time response time will be slower than usual.

**Comment by telpirion** [comment]
Hello @edumotya,

I have some follow-up questions for you:
+ Have you tried processing a document with italic font, per [here](https://cloud.google.com/document-ai/docs/reference/rpc/google.cloud.documentai.v1beta3#style)?
+ What types of processor(s) have you used?

**Comment by edumotya** [comment]
Hello @telpirion, I have processed several documents with a wide variety of fonts, including italic and bold fonts. I always use the invoice parser processor.

**Comment by edumotya** [comment]
Hi @telpirion @munkhuushmgl,

Thank you for looking at this, any updates?
