### ISSUE TITLE
cannot import name 'documentai_v1beta3' from 'google.cloud' (unknown location)

### ISSUE THREAD

**Issue by jimwill3** [googleapis/python-documentai#81]
#### Environment details

  - OS type and version: NAME="Ubuntu" VERSION="18.04.5
  - Python version: Python 3.7.8
  - pip version: pip 20.2.4 from /opt/conda/lib/python3.7/site-packages/pip (python 3.7)
  - `google-cloud-documentai` version: Version: 0.3.0

#### Steps to reproduce
using jupyter notebook hosted in Google Cloud Notebook Instance
from google.cloud import documentai_v1beta3 as documentai
Error:
ImportError: cannot import name 'documentai_v1beta3' from 'google.cloud' (unknown location)

**Comment by munkhuushmgl** [comment]
I was able to run it without any problem:
![image](https://user-images.githubusercontent.com/45373284/104055902-68d1d300-51a4-11eb-814a-d8a578828239.png)

Steps I took:
1. Create notebook instance on Google Cloud (customized to use Ubuntu 18.04)
2. Open terminal and check python and pip versions (python3.7.9 and pip==20.3.3)
3. open python3 terminal
4. run the following code in the python terminal
```
from google.cloud import documentai_v1beta3 as documentai
```

**Comment by munkhuushmgl** [comment]
even in the notebook, it works fine

**Comment by munkhuushmgl** [comment]
@jimwill3 I do not think there is anything wrong with document AI API or this repo.

**Comment by jimwill3** [comment]
interesting - thanks for testing. i continue to see failures in multiple environments, a local mac, and the notebook instance in GCP. my install of the library was also successful so I'm a bit stumped. Did your test occur on a very recently created GCP notebook instance? 
thanks,
jim

**Comment by munkhuushmgl** [comment]
> iDid your test occur on a very recently created GCP notebook instance?
Yes, i just created new instance to repro this issue

**Comment by jimwill3** [comment]
maybe that's a factor. i just uninstalled and reinstalled the package - restarted the kernel etc. but w/o any success.
 Successfully uninstalled google-cloud-documentai-0.3.0
(base) root@1669429b6d4a:/# pip install   google-cloud-documentai==0.3.0
Collecting google-cloud-documentai==0.3.0
  Using cached google_cloud_documentai-0.3.0-py2.py3-none-any.whl (105 kB)
Requirement already satisfied: google-api-core[grpc]<2.0.0dev,>=1.22.0 in /opt/conda/lib/python3.7/site-packages (from google-cloud-documentai==0.3.0) (1.22.4)
Requirement already satisfied: proto-plus>=1.10.0 in /opt/conda/lib/python3.7/site-packages (from google-cloud-documentai==0.3.0) (1.13.0)
Requirement already satisfied: googleapis-common-protos<2.0dev,>=1.6.0 in /opt/conda/lib/python3.7/site-packages (from google-api-core[grpc]<2.0.0dev,>=1.22.0->google-cloud-documentai==0.3.0) (1.52.0)
Requirement already satisfied: google-auth<2.0dev,>=1.21.1 in /opt/conda/lib/python3.7/site-packages (from google-api-core[grpc]<2.0.0dev,>=1.22.0->google-cloud-documentai==0.3.0) (1.23.0)
Requirement already satisfied: setuptools>=34.0.0 in /opt/conda/lib/python3.7/site-packages (from google-api-core[grpc]<2.0.0dev,>=1.22.0->google-cloud-documentai==0.3.0) (49.6.0.post20201009)
Requirement already satisfied: six>=1.13.0 in /opt/conda/lib/python3.7/site-packages (from google-api-core[grpc]<2.0.0dev,>=1.22.0->google-cloud-documentai==0.3.0) (1.15.0)
Requirement already satisfied: requests<3.0.0dev,>=2.18.0 in /opt/conda/lib/python3.7/site-packages (from google-api-core[grpc]<2.0.0dev,>=1.22.0->google-cloud-documentai==0.3.0) (2.24.0)
Requirement already satisfied: protobuf>=3.12.0 in /opt/conda/lib/python3.7/site-packages (from google-api-core[grpc]<2.0.0dev,>=1.22.0->google-cloud-documentai==0.3.0) (3.13.0)
Requirement already satisfied: pytz in /opt/conda/lib/python3.7/site-packages (from google-api-core[grpc]<2.0.0dev,>=1.22.0->google-cloud-documentai==0.3.0) (2020.1)
Requirement already satisfied: grpcio<2.0dev,>=1.29.0; extra == "grpc" in /opt/conda/lib/python3.7/site-packages (from google-api-core[grpc]<2.0.0dev,>=1.22.0->google-cloud-documentai==0.3.0) (1.33.2)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in /opt/conda/lib/python3.7/site-packages (from google-auth<2.0dev,>=1.21.1->google-api-core[grpc]<2.0.0dev,>=1.22.0->google-cloud-documentai==0.3.0) (4.1.1)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /opt/conda/lib/python3.7/site-packages (from google-auth<2.0dev,>=1.21.1->google-api-core[grpc]<2.0.0dev,>=1.22.0->google-cloud-documentai==0.3.0) (0.2.7)
Requirement already satisfied: rsa<5,>=3.1.4; python_version >= "3.5" in /opt/conda/lib/python3.7/site-packages (from google-auth<2.0dev,>=1.21.1->google-api-core[grpc]<2.0.0dev,>=1.22.0->google-cloud-documentai==0.3.0) (4.6)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /opt/conda/lib/python3.7/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core[grpc]<2.0.0dev,>=1.22.0->google-cloud-documentai==0.3.0) (1.25.11)
Requirement already satisfied: chardet<4,>=3.0.2 in /opt/conda/lib/python3.7/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core[grpc]<2.0.0dev,>=1.22.0->google-cloud-documentai==0.3.0) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.7/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core[grpc]<2.0.0dev,>=1.22.0->google-cloud-documentai==0.3.0) (2020.6.20)
Requirement already satisfied: idna<3,>=2.5 in /opt/conda/lib/python3.7/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core[grpc]<2.0.0dev,>=1.22.0->google-cloud-documentai==0.3.0) (2.10)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /opt/conda/lib/python3.7/site-packages (from pyasn1-modules>=0.2.1->google-auth<2.0dev,>=1.21.1->google-api-core[grpc]<2.0.0dev,>=1.22.0->google-cloud-documentai==0.3.0) (0.4.8)
Installing collected packages: google-cloud-documentai
Successfully installed google-cloud-documentai-0.3.0

go back to notebook - restart the kernel - same error message.
i will look to create a fresh notebook instance and see if that clears things up.
thanks,
jim

**Comment by jimwill3** [comment]
After digging around discovered that the GCP notebook instance I selected was pre-loaded for Apache-Beam (which I intended to use as part of a text project along with documentai), however, the executable path for notebooks (jupyter kernelspec list) did not include the path where all the other packages are installed by default. So, it's ugly, but to get moving I added this crude hack to my notebook:
print(sys.executable)                                                                       #returns /root/apache-beam-custom/bin/python
sys.path.append('/opt/conda/lib/python3.7/site-packages/').    #total hack 
thanks,
jim
