### ISSUE TITLE
OCR symbols

### ISSUE THREAD

**Issue by edumotya** [googleapis/python-documentai#86]
We need the OCR symbols (characters) for some extra processing. Currently, the documentai response includes: blocks, paragraphs, lines and tokens (equivalent to words). Do you think you can add the OCR symbols to the response?

**Comment by munkhuushmgl** [comment]
I will inform this to the internal team. Once I get a update, I will circle back to you.

**Comment by munkhuushmgl** [comment]
For future feature request, Please use open public issue tracker.

With that note, I am closing this issue.
